name: zaffy
dependencies:
- certifi=2016.2.28=py27_0
- chardet=2.3.0=py27_0
- colorama=0.3.7=py27_0
- jinja2=2.8=py27_1
- openssl=1.0.2h
- pip=8.1.2=py27_0
- python=2.7.12
- python-dateutil=2.5.3=py27_0
- pyyaml=3.11=py27_4
- requests=2.10.0=py27_0
- setuptools=23.0.0=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0
- paramiko=1.16.0=py27_0
- pymysql=0.6.7=py27_0
- lxml=3.6.0=py27_0
- pip:
  - bottle==0.12.9
  - pymemcache==1.3.5
